profile page - needs refactoring
nightlight-app/nightlight-frontend pull request #3
Opened 2023-02-10 21:32 UTC by sophiabrent

2023-02-21 20:30 UTC, zineanteoh commented
looks ready to merge from my end -- @sophiabrent @ethanratnofsky please review

2023-02-22 03:24 UTC, ethanratnofsky requested changes

2023-02-22 03:24 UTC, ethanratnofsky commented on src/screens/profile/ProfileScreen.styles.ts
> +    color: '#A6A6A6',
```suggestion
    color: COLORS.GRAY,
```

2023-02-22 03:24 UTC, ethanratnofsky commented on src/screens/profile/ProfileScreen.styles.ts
> +    top: 0,
use position absolute sparingly!! probably don't need this here

2023-02-22 03:24 UTC, ethanratnofsky commented on src/screens/profile/ProfileScreen.styles.ts
> +  },
this can be positioned absolutely

2023-02-22 03:24 UTC, ethanratnofsky commented on src/screens/profile/ProfileScreen.tsx
> +            <Button color={'white'} title='View Emergency Contacts' />
use Pressable instead of Button

2023-02-22 04:54 UTC, zineanteoh commented
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58854510/220525455-723aa441-e14a-49ae-83b5-f2290a845573.png">

2023-02-22 05:00 UTC, ethanratnofsky approved these changes

2023-02-22 05:00 UTC, merged